---
title: "Tarea 5: 18/09/2017"
output: html_notebook
---
## Tarea 5: 18/09/2017
_175904 - Jorge III Altamirano Astorga_

```{r librerías, message=FALSE, warning=FALSE, error=TRUE}
library(readr)
library(tidyr)
library(dplyr)
library(tabplot)
library(ROCR)
library(ggplot2)
library(glmnet)
set.seed(175904)
```

### Carga de datos de SPAM

Tomado de [spambase](https://archive.ics.uci.edu/ml/datasets/spambase)
```{r init & standarization, message=FALSE, warning=FALSE}
spam_entrena <- read_csv('spam-entrena.csv')
spam_prueba <- read_csv('spam-prueba.csv')
spam_entrena$spam <- parse_integer(spam_entrena$spam)
spam_prueba$spam <- parse_integer(spam_prueba$spam)

## Tomado de https://stackoverflow.com/questions/15215457/standardize-data-columns-in-r
columnas_normalizadas <- c("wfmake", "wfaddress", "wfall", "wf3d", "wfour", "wfover", "wfremove", "wfinternet", "wforder", "wfmail", "wfreceive", "wfwill", "wfpeople", "wfreport", "wfaddresses", "wffree", "wfbusiness", "wfemail", "wfyou", "wfcredit", "wfyour", "wffont", "wf000", "wfmoney", "wfhp", "wfhpl", "wfgeorge", "wf650", "wflab", "wflabs", "wftelnet", "wf857", "wfdata", "wf415", "wf85", "wftechnology", "wf1999", "wfparts", "wfpm", "wfdirect", "wfcs", "wfmeeting", "wforiginal", "wfproject", "wfre", "wfedu", "wftable", "wfconference", "cfsc", "cfpar", "cfbrack", "cfexc", "cfdollar", "cfpound", "crlaverage", "crllongest", "crltotal")
spam_entrena2 <- spam_entrena %>% mutate_each_(funs(scale(.) %>% as.vector),
   vars=columnas_normalizadas)
spam_prueba2 <- spam_prueba %>% mutate_each_(funs(scale(.) %>% as.vector),
   vars=columnas_normalizadas)
```

```{r ridge}
x_e <- spam_entrena2 %>% select(-spam, -X1) %>% as.matrix
x_p <- spam_prueba2 %>% select(-spam, -X1) %>% as.matrix
mod_ridge <- glmnet(x = x_e, y = spam_entrena2$spam,
    alpha = 0, family = "binomial", intercept = FALSE, nlambda = 50)
dim(coef(mod_ridge))
plot(mod_ridge, xvar = 'lambda')
```

```{r Probabilidades para los n modelos}
# predict en glmnet produce probabilidades para los n modelos
preds_ridge <- predict(mod_ridge, newx = x_p, type = 'response') %>%
  data.frame %>% mutate(X1 = 1:nrow(x_p)) %>%
  gather(modelo, prob, -X1) %>%
  # this didn't work! :-P
  # left_join(spam_prueba2 %>% mutate(X1=1:nrow(spam_prueba2)) %>% select(X1, spam)) #%>%
  inner_join(spam_prueba2 %>% mutate(X1=1:nrow(spam_prueba2)) %>% select(X1, spam))
summary(preds_ridge)
paste("Rows: ", nrow(preds_ridge))
```

```{r lambdas, warning=FALSE, message=FALSE}
devianza  <- function(p, y){
  -2*mean(y * log(p) + (1-y) * log(1 - p))
}
df_lambdas <- data_frame(modelo = attr(mod_ridge$a0, 'names'), 
                         lambda = mod_ridge$lambda)
devianzas_prueba <- preds_ridge %>% group_by(modelo) %>%
    summarise(devianza = devianza(prob, spam)) %>% inner_join(df_lambdas)
# summary(devianzas_prueba)
ggplot(devianzas_prueba, aes(x = lambda, y= devianza)) + 
  scale_x_log10(breaks = round(2^seq(-5,5,1),2)) +
  geom_point()

```

```{r}
devianzas_prueba %>% filter(devianza < 55e-2)
```

### Coeficientes

```{r}
h <- function(x){ 1 / (1 + exp(-x))}
coefs_selec <- coef(mod_ridge)[-1, 's49']
coefs_selec
pred_prueba_final <- h(x_p %*% coefs_selec)
tab_confusion <- table(pred_prueba_final > 0.24, spam_prueba2$spam)
tab_confusion
```
