---
title: "Examen Final"
output: html_notebook
---

```{r libs, include=FALSE}
library(tidyverse)
library(jsonlite)
library(plyr)
```

```{r}
df <- fromJSON("data/train.json") 
df <- df %>% as.data.frame
```

```{r}
train_n <- sample(nrow(df)*.7, replace = FALSE)
train_data <- df[train_n,]
test_data <- df[-train_n,]
```

```{r}
ingredients_train <- train_data[,3] %>% 
  unlist %>% trimws
```

```{r}
unimportant_words <- "(^a taste of|any|low-fat|all|powder|baby|bertolli|boiled|boiling|bone in|whole|boneless|bottled|sauvignon|california|campbells condensed|canned|chopped|flavored carbonated beverage|cold|condensed|cooked|cooking|cereal|lowfat|frosting|spread|soften|with chives.*|ic peach| of .*|creamed|creamy| mexican.?|crushed|crystal farms|shredded|crystallized|crystal hot|cubed|curly|curlyleaf|jelly|dessert mix|sauce mix|mix|dark|dellallo|deepfried|deep fried|diced|diet|tortilla chips||domino|dried|minced|dry|earth balance|elmlea|^english|evaporated|everglades|extra fine|extra firm|extra large|extra\\s?lean|extra light|extra sharp|extra\\s?virgin|extra wide|^fat|fat\\s?free|fat skimmed|fatfree?|fattrimmed|fine|firm|firmly packed|flat |^flavored|terrine|food|free\\s?range|^french|^fresh| root|^fresno|^fried|^frozen|^fuji|full\\s?fat|gluten\\s?free|s milk |^gold|golden|gourmet|graham|granulated|grassfed|grated|grating|gravenstein|great|greater|style|green|grilled|grill|ground|half|heavy|heinz|hellmanns?|of the woods|herbed |herdez|hidden valley|homemade|^hot |hot smoked|hot spanish|^hungarian|hurst|i cantbelieve? its? not butter|imitation|imperial sugar light brown|instant |^irish|^italian|italianstyle|^japanese |jimmy dean|johnsonville|jose cuervo|jumbo|kikkoman|knorr|knudsen|kraft|mexican style|kraft zesty|slim cut|sun dried|shredded|la victoria|land o lakes|^large|^lean|leftover|leg of|zest|less sodium|lesser|leaves|^light|cook and drain|lipton|liquid |^lite|^long |loosely packed fresh|low fat|lowfat|^low sodium|lower sodium|lowfat|baked|\\sdeli|firm silken|styl|lowsodium|and cheese dinner|madagascar bourbon|extract|mccormick|^medium|uncook|uncooked|merguez|^mexican|minced|mini|mini|mixed|mixture|mizkan|^mms|mrs dash|natural|^nido|non dairy|non fat|non stick|nondairy|nonfat|frozen|nonhydrogenated|nosaltadded|old el paso|old|old\\s?fashioned|cooking spray|flavored|^organic|oscar mayer|other|oven\\s?ready|flavor|flavour|paella|reggiano|peeled|^petite|pillsbury|powdered|prepared|preserv|preserved|progresso|\\sdi\\sparma|pt|pte|puff|puffed|pure|quickcooking|quick|cooking|raw|red|reduced\\sfat|reduced\\ssodium|reduced\\ssugar|reducedfat|reducedsodium|reducedsugar|refrigerated|regular|rich|roasted|roast|roasting|robert mondavi|salt free seasoning|salt free chili powder|salt free cajun creole seasoning|salt free southwest chipotle seasoning|salt free herb seasoning|salt free chili powder|salted|saltines?|saltpeper|san marazano|sargento|links|casings|savoy|seafood|seasoned|seasoning|seedless|self ?ra?ising|shredded|single|simple|skinless|sliced|small|smoked|sodium free|sodium reduced|soft|softened|solid|southern comfort.*|southwest|sparkling|spicy|splenda.*|split|spring water|^strip|superfine|sweetened|taco bell.*|into serving pieces|to\\s+lb|toasted|uncle bens|^uncook|^uncooked|unflavou?red|unsweetened|white|wholesome sweeteners|wholemilk|wide|^wild|^winter|wish\\s?bone|yellow|young|zesty|italian|all ?purpose|puree|juice|aged|tuna in water|liqueur|liquor|^asian|and .*|yoplait)(\\s|$)"

ingredients_train <- ingredients_train %>%
  tolower %>%
  gsub("\\([^)]*\\)", "", ., perl = T, ignore.case = T) %>%
  gsub("[^ a-z]", "", ., perl = T, ignore.case = T) %>%
  gsub("^\\s+", "", ., perl = T, ignore.case = T) %>%
  gsub(unimportant_words, " ", ., perl = T, ignore.case = T) %>%
  gsub("\\s+", " ", ., perl = T, ignore.case = T) %>%
  gsub("^\\s+", "", ., perl = T, ignore.case = T) %>%
  trimws()

ingredients_train<- ingredients_train[which(!grepl(pattern = "^$", x = ingredients_train))] 

```


```{r}
ingredients_train_gr <- as.data.frame(ingredients_train, stringsAsFactors = FALSE) %>%
  group_by(ingredients_train)

ingredients_train_uq <- ingredients_train %>% unique

ingredients_count <-ingredients_train_gr %>% 
  count %>%
  arrange(freq) %>%
  cbind(ident = c(1:length(ingredients_train_uq)))

head(ingredients_count)
tail(ingredients_count)
length(ingredients_train_uq)

```

```{r}
ggplot(ingredients_count,aes(x=ident, y=freq))+geom_line() +scale_y_log10()
```

```{r}
ingredients_min <- ingredients_train_gr[ingredients_count>20,] %>% unique %>% ungroup
ingredients_test <- sapply(1:1000,function(i){
  ingredients_count[ingredients_count$freq>i,]  %>% nrow
})

plot(ingredients_test)
```

```{r}
ggplot(train_data, aes(x =cuisine)) +
  geom_histogram(stat="count") +
  theme(axis.text.x=element_text(angle=90,hjust=1))
```

```{r}
train_nd <- train_data %>% ungroup
train_nd$ingredients <- lapply(train_nd$ingredients,unique)
train_nd$ingredients[1]
```

```{r}
train_nd$ingredients <-sapply(1:nrow(train_nd),function(i){ train_nd$ingredients[[i]][train_nd$ingredients[[i]] %in% (ingredients_min$ingredients_train)] })
```

```{r}
train_id_ing <- train_nd %>% unnest %>% subset(select = c("id","ingredients"))
train_id_ing <- train_id_ing %>% cbind(number = rep(1,nrow(train_id_ing))) %>% group_by(id)
train_id_ing <- train_id_ing[!duplicated(train_id_ing[c("id","ingredients")]),]
train_id_ing <- train_id_ing %>% spread(key = ingredients, value=number, fill = 0)
train_x <- train_id_ing[,-1] %>% data.frame

train_y <- train_nd %>% unnest %>% subset(select = c("id","cuisine")) %>% unique
train_y <- data.frame(Cuisine = train_y$cuisine, stringsAsFactors = FALSE)

nrow(train_x)
nrow(train_y)

head(train_x)
head(train_y)
```
## Test Data
```{r}
test_nd <- test_data %>% ungroup
test_nd$ingredients <- lapply(test_nd$ingredients,unique)

```

```{r}
test_nd$ingredients <-sapply(1:nrow(test_nd),function(i){ test_nd$ingredients[[i]][test_nd$ingredients[[i]] %in% (ingredients_min$ingredients_train)] })

test_id_ing <- test_nd %>% unnest %>% subset(select = c("id","ingredients"))
test_id_ing <- test_id_ing %>% cbind(number = rep(1,nrow(test_id_ing))) %>% group_by(id)
test_id_ing <- test_id_ing[!duplicated(test_id_ing[c("id","ingredients")]),]
test_id_ing <- test_id_ing %>% spread(key = ingredients, value=number, fill = 0)
test_x <- test_id_ing[,-1] %>% data.frame

test_y <- test_nd %>% unnest %>% subset(select = c("id","cuisine")) %>% unique
test_y <- data.frame(Cuisine = test_y$cuisine, stringsAsFactors = FALSE)

nrow(train_x)
nrow(test_x)

head(train_x)
head(test_x)

```

```{r}
names_column_test <- names(train_x)[!(names(train_x) %in% names(test_x))]
column_test <- matrix(0,nrow = nrow(train_x),ncol = length(names_column_test)) %>% data.frame
names(column_test) <- names_column_test

test_x <- join(test_x,column_test)[,names(train_x)]
test_x[is.na(test_x)] <- 0
nrow(train_x)
nrow(test_x)

head(train_x)
head(test_x)
```
```{r}
sum(!names(train_x)==names(test_x))
```



```{r}
save(train_x,file = "train_x.RData")
save(train_y,file = "train_y.RData")

save(test_x,file = "test_x.RData")
save(test_y,file = "test_y.RData")


```

