---
title: "Examen Final"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
library(jsonlite)
library(plyr)
# install.packages("ngram")
library(ngram)
```

```{r}
train <- fromJSON("data/train.json") 
train <- train %>% as.data.frame
train_2 <- train
train_3 <- train
ingredients <-unlist(train_3[,3])

## Código original Uriel
# ingredients <- ingredients %>%
#   unique

## Código Regex Jorge
unimportant_words <- "(^a taste of|any|low-fat|all|powder|baby|bertolli|boiled|boiling|bone in|whole|boneless|bottled|sauvignon|california|campbells condensed|canned|chopped|flavored carbonated beverage|cold|condensed|cooked|cooking|cereal|lowfat|frosting|spread|soften|with chives.*|ic peach| of .*|creamed|creamy| mexican.?|crushed|crystal farms|shredded|crystallized|crystal hot|cubed|curly|curlyleaf|jelly|dessert mix|sauce mix|mix|dark|dellallo|deepfried|deep fried|diced|diet|tortilla chips||domino|dried|minced|dry|earth balance|elmlea|^english|evaporated|everglades|extra fine|extra firm|extra large|extra\\s?lean|extra light|extra sharp|extra\\s?virgin|extra wide|^fat|fat\\s?free|fat skimmed|fatfree?|fattrimmed|fine|firm|firmly packed|flat |^flavored|terrine|food|free\\s?range|^french|^fresh| root|^fresno|^fried|^frozen|^fuji|full\\s?fat|gluten\\s?free|s milk |^gold|golden|gourmet|graham|granulated|grassfed|grated|grating|gravenstein|great|greater|style|green|grilled|grill|ground|half|heavy|heinz|hellmanns?|of the woods|herbed |herdez|hidden valley|homemade|^hot |hot smoked|hot spanish|^hungarian|hurst|i cantbelieve? its? not butter|imitation|imperial sugar light brown|instant |^irish|^italian|italianstyle|^japanese |jimmy dean|johnsonville|jose cuervo|jumbo|kikkoman|knorr|knudsen|kraft|mexican style|kraft zesty|slim cut|sun dried|shredded|la victoria|land o lakes|^large|^lean|leftover|leg of|zest|less sodium|lesser|leaves|^light|cook and drain|lipton|liquid |^lite|^long |loosely packed fresh|low fat|lowfat|^low sodium|lower sodium|lowfat|baked|\\sdeli|firm silken|styl|lowsodium|and cheese dinner|madagascar bourbon|extract|mccormick|^medium|uncook|uncooked|merguez|^mexican|minced|mini|mini|mixed|mixture|mizkan|^mms|mrs dash|natural|^nido|non dairy|non fat|non stick|nondairy|nonfat|frozen|nonhydrogenated|nosaltadded|old el paso|old|old\\s?fashioned|cooking spray|flavored|^organic|oscar mayer|other|oven\\s?ready|flavor|flavour|paella|reggiano|peeled|^petite|pillsbury|powdered|prepared|preserv|preserved|progresso|\\sdi\\sparma|pt|pte|puff|puffed|pure|quickcooking|quick|cooking|raw|red|reduced\\sfat|reduced\\ssodium|reduced\\ssugar|reducedfat|reducedsodium|reducedsugar|refrigerated|regular|rich|roasted|roast|roasting|robert mondavi|salt free seasoning|salt free chili powder|salt free cajun creole seasoning|salt free southwest chipotle seasoning|salt free herb seasoning|salt free chili powder|salted|saltines?|saltpeper|san marazano|sargento|links|casings|savoy|seafood|seasoned|seasoning|seedless|self ?ra?ising|shredded|single|simple|skinless|sliced|small|smoked|sodium free|sodium reduced|soft|softened|solid|southern comfort.*|southwest|sparkling|spicy|splenda.*|split|spring water|^strip|superfine|sweetened|taco bell.*|into serving pieces|to\\s+lb|toasted|uncle bens|^uncook|^uncooked|unflavou?red|unsweetened|white|wholesome sweeteners|wholemilk|wide|^wild|^winter|wish\\s?bone|yellow|young|zesty|italian|all ?purpose|puree|juice|aged|tuna in water|liqueur|liquor|^asian|and .*|yoplait)(\\s|$)"
ingredients <- ingredients %>%
  # unlist %>%
  tolower %>%
  gsub("\\([^)]*\\)", "", ., perl = T, ignore.case = T) %>%
  gsub("[^ a-z]", "", ., perl = T, ignore.case = T) %>%
  gsub("^\\s+", "", ., perl = T, ignore.case = T) %>%
  gsub(unimportant_words, " ", ., perl = T, ignore.case = T) %>%
  gsub("\\s+", " ", ., perl = T, ignore.case = T) %>%
  gsub("^\\s+", "", ., perl = T, ignore.case = T) %>%
  trimws %>%
  unique # %>%
  # data_frame(x = .) %>%
  # arrange(x)
ingredients <- ingredients[which(!grepl(pattern = "^$", x = ingredients))]

ingredients_df <- data.frame(ing = ingredients, stringsAsFactors = FALSE) %>%
  group_by(ing)
ingredients_count <-ingredients_df %>% 
  count %>%
  arrange(freq) %>%
  cbind(ident = c(1:length(ingredients)))

head(ingredients_count)
tail(ingredients_count)
```
```{r}
ggplot(ingredients_count,aes(x=ident, y=freq))+geom_line() +scale_y_log10()
```


```{r}
ggplot(train_3, aes(x =cuisine)) +
  geom_histogram(stat="count") +
  theme(axis.text.x=element_text(angle=90,hjust=1))
```
```{r}
n_ing <- train_3$ingredients
a_ing <- sapply(1:length(n_ing),function(i){length(n_ing[[i]])}) 
train_3$n_ing <- a_ing
head(train_3)
```


```{r}
freq_an <- data.frame( Cuisine = unique(train_3$cuisine), 
                       Mean = aggregate(train_3$n_ing, list(train_3$cuisine), mean)[,2],
                       SD = aggregate(train_3$n_ing, list(train_3$cuisine), sd)[,2],
                       Min = aggregate(train_3$n_ing, list(train_3$cuisine), min)[,2],
                       Max = aggregate(train_3$n_ing, list(train_3$cuisine), max)[,2])

freq_an
```

```{r}
myplot <- ggplot(train_3, aes(n_ing, group = cuisine)) + 
          geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
          scale_y_continuous(labels=scales::percent) +
          ylab("relative frequencies") +
          facet_wrap(~cuisine)
myplot
```

```{r}
train_3 <- train %>% unnest %>% subset(select = c("id","ingredients"))
train_3 <- train_3 %>% cbind(number = rep(1,nrow(train_3))) %>% group_by(id)
train_4 <- train_3[!duplicated(train_3[c("id","ingredients")]),]
train_4 <- train_4 %>% spread(key = ingredients, value=number, fill = 0)
dim(train_4)
```


##=============================================================================================================
## Variable Ingredientes

```{r}
ingredients_df_all <- data.frame(ingredients = ingredients,stringsAsFactors=FALSE)
ingredients_df_all <- ingredients_df_all %>% cbind (word_count = sapply(1:length(ingredients),function(i){wordcount(ingredients[i])}) ) %>% data.frame(stringsAsFactors=FALSE) 
arrange(count(a$word_count),x)
one_word_ingredients <-ingredients_df_all[ingredients_df_all$word_count==1,]$ingredients
one_word_ingredients <- gsub(" ", "", one_word_ingredients, fixed = TRUE) %>% data.frame(stringsAsFactors=FALSE)
more_word_ingredients <- ingredients_df_all[ingredients_df_all$word_count>1,]
```


