---
title: "Examen Final"
output: html_notebook
---



```{r libs, include=FALSE}
library(plyr)
library(tidyverse)
library(jsonlite)
library(rpart)
library(rpart.plot)
library(randomForest)
```


```{r import}
train <- fromJSON("data/train.json") 
train <- train %>% as.data.frame
train_2 <- train
```

```{r clean_ingredients}
unimportant_words <- "(^a taste of|any|low-fat|low ?salt|all|powder|baby|bertolli|boiled|boiling|bone in|whole|boneless|bottled|sauvignon|california|campbells condensed|canned|chopped|flavored carbonated beverage|cold|condensed|cooked|cooking|cereal|lowfat|frosting|spread|soften|with chives.*|ic peach| of .*|creamed|creamy| mexican.?|crushed|crystal farms|shredded|crystallized|crystal hot|cubed|curly|curlyleaf|jelly|dessert mix|sauce mix|mix|dark|dellallo|deepfried|deep fried|diced|diet|tortilla chips||domino|dried|minced|dry|earth balance|elmlea|^english|evaporated|everglades|extra fine|extra firm|extra large|extra\\s?lean|extra light|extra sharp|extra\\s?virgin|extra wide|^fat|fat\\s?free|fat skimmed|fatfree?|fattrimmed|fine|firm|firmly packed|flat |^flavored|terrine|food|free\\s?range|^french|^fresh| root|^fresno|^fried|^frozen|^fuji|full\\s?fat|gluten\\s?free|s milk |^gold|golden|gourmet|graham|granulated|grassfed|grated|grating|gravenstein|great|greater|style|green|grilled|grill|ground|half|heavy|heinz|hellmanns?|of the woods|herbed |herdez|hidden valley|homemade|^hot |hot smoked|hot spanish|^hungarian|hurst|i cantbelieve? its? not butter|imitation|imperial sugar light brown|instant |^irish|^italian|italianstyle|^japanese |jimmy dean|johnsonville|jose cuervo|jumbo|kikkoman|knorr|knudsen|kraft|mexican style|kraft zesty|slim cut|sun dried|shredded|la victoria|land o lakes|^large|^lean|leftover|leg of|zest|less sodium|lesser|leaves|^light|cook and drain|lipton|liquid |^lite|^long |loosely packed fresh|low fat|lowfat|^low sodium|lower sodium|lowfat|baked|\\sdeli|firm silken|styl|lowsodium|and cheese dinner|madagascar bourbon|extract|mccormick|^medium|uncook|uncooked|merguez|^mexican|minced|mini|mini|mixed|mixture|mizkan|^mms|mrs dash|natural|^nido|non dairy|non fat|non stick|nondairy|nonfat|frozen|nonhydrogenated|nosaltadded|old el paso|old|old\\s?fashioned|cooking spray|flavored|^organic|oscar mayer|other|oven\\s?ready|flavor|flavour|paella|reggiano|peeled|^petite|pillsbury|powdered|prepared|preserv|preserved|progresso|\\sdi\\sparma|pt|pte|puff|puffed|pure|quickcooking|quick|cooking|raw|red|reduced\\sfat|reduced\\ssodium|reduced\\ssugar|reducedfat|reducedsodium|reducedsugar|refrigerated|regular|rich|roasted|roast|roasting|robert mondavi|salt free seasoning|salt free chili powder|salt free cajun creole seasoning|salt free southwest chipotle seasoning|salt free herb seasoning|salt free chili powder|salted|saltines?|saltpeper|san marazano|sargento|links|casings|savoy|seafood|seasoned|seasoning|seedless|self ?ra?ising|shredded|single|simple|skinless|sliced|small|smoked|sodium free|sodium reduced|soft|softened|solid|southern comfort.*|southwest|sparkling|spicy|splenda.*|split|spring water|^strip|superfine|sweetened|taco bell.*|into serving pieces|to\\s+lb|toasted|uncle bens|^uncook|^uncooked|unflavou?red|unsweetened|white|wholesome sweeteners|wholemilk|wide|^wild|^winter|wish\\s?bone|yellow|young|zesty|part ?skim|italian|all ?purpose|puree|juice|aged|tuna in water|liqueur|liquor|^asian|and .*|yoplait|greek|fresh|spray|hot water|warm water|crumbles|freshly|flakes?|unsalt|unsalted|wedges?|plain)(\\s|$)"
popular_words <- function(a){
  a <- gsub("(.*)(beans?|lettuce|olives?|tabasco|potato(es)?|cilantro|wheat|shiitake|lemon|chives?|tomato(es)?|cabbage|peanut|yogh?o?urt|rice|onions?|ginger|sesame|jalapeno|stock|bacon|monterey_jack|vinegar|sausages?|mozz?arell?a|monterey_jack|feta|ricotta|dijon|masala|eggs?|coconut_milk|cheddar|dijon|parmesan|sour_(crema|cream)|steak|pork|beef|chicken|oyster|garlic|salt|curry).*", "\\2", a)
}

#limpiar datos de ingredientes
train_2$ingredients <- sapply(1:nrow(train), function(x) {
  train[x,3] %>% 
    unlist %>%
    tolower %>%
    gsub("\\([^)]*\\)", "", ., perl = T, ignore.case = T) %>%
    gsub("[^ a-z]", "", ., perl = T, ignore.case = T) %>%
    gsub("^\\s+", " ", ., perl = T, ignore.case = T) %>%
    gsub(unimportant_words, " ", ., perl = T, ignore.case = T) %>%
    gsub("\\s+", " ", ., perl = T, ignore.case = T) %>%
    unique %>%
    trimws %>%
    gsub("\\s", "_", ., perl = T, ignore.case = T) %>%
    popular_words
})

train_2$cuisine <- train_2$cuisine %>% as.factor
glimpse(train_2)

ingredients <- train_2$ingredients %>% 
  unlist 
ingredients <- ingredients[which(!grepl(pattern = "^$", x = ingredients))] #%>%
#    unique
ingredients %>% head(n=10)

ingredients_df <- as.data.frame(ingredients, stringsAsFactors = F) %>%
  group_by(ingredients)

ingredients_count <- ingredients_df %>% 
  plyr::count(.) %>%
  arrange(freq)
ingredients_count$id <- 1:nrow(ingredients_count)
head(ingredients_count)
tail(ingredients_count)
```


```{r}
ggplot(ingredients_count %>% filter(freq > 100),aes(x=id, y=log(freq)))+geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
ingredients_top <- ingredients_count %>% filter(freq > 120) %>% select(ingredients) 
```

```{r}
# train_3 <- train_2[,1:2]
# glimpse(train_2)
# #crea las columnas
# train_3[, ingredients_top %>% unlist] <- 0
# for(i in 1:nrow(train_3)){
#   train_3[i, which(names(train_3) %in% (train_2[i,]$ingredients %>% unlist))] <- 1
# }
# rm(i)
# saveRDS(train_2, "data/train_2.rds")
# saveRDS(train_3, "data/train_3.rds")
train_2 <- readRDS("data/train_2.rds")
train_3 <- readRDS("data/train_3.rds")
train_3 %>% select(id,cuisine,garlic,salt,pepper)
```
### Bin Tree

```{r}
arbol_grande <- rpart(cuisine ~ ., data= train_3[,-1], cp=0)
prp(prune(arbol_grande, cp=0.03), type=4, extra=1, digits=3) 
```

### Random Forest

```{r}
bosque <- randomForest(cuisine ~ .,
                       data = train_3 %>% select(-id), 
                       ntree = 1500, mtry = 50, importance = T)
```

### Other

```{r}
n_ing <- train_2$ingredients
# a_ing <- 
train_2$n_ing <- sapply(1:length(n_ing),function(i){length(n_ing[[i]])})
ggplot(train_2 , aes(x=cuisine,y=n_ing)) +
  geom_boxplot() +
  theme(axis.text.x=element_text(angle=90,hjust=1))
```


```{r}
freq_an <- data.frame( Cuisine = unique(train_2$cuisine), 
                       Mean = aggregate(train_2$n_ing, list(train_2$cuisine), mean)[,2],
                       SD = aggregate(train_2$n_ing, list(train_2$cuisine), sd)[,2],
                       Min = aggregate(train_2$n_ing, list(train_2$cuisine), min)[,2],
                       Max = aggregate(train_2$n_ing, list(train_2$cuisine), max)[,2])
freq_an
```

```{r}
ggplot(train_2, aes(n_ing, group = cuisine)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
    scale_y_continuous(labels=scales::percent) +
    ylab("relative frequencies") +
    facet_wrap(~cuisine)
```


```{r}
ggplot(train_2$cuisine %>% count, aes(x = reorder(x, freq), y = freq)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x=element_text(angle=90,hjust=1))
```

```{r}
train_3 <- train_2 %>% unnest %>% subset(select = c("id","ingredients"))
train_3 <- train_2 %>% cbind(number = rep(1,nrow(train_3))) %>% group_by(id)
train_4 <- train_3[!duplicated(train_3[c("id","ingredients")]),]
train_4 <- train_4 %>% spread(key = ingredients, value=number, fill = 0)
dim(train_4)
```


<hr>
## Variable Ingredientes

```{r}
ingredients_df_all <- data.frame(ingredients = ingredients,stringsAsFactors=FALSE)
ingredients_df_all <- ingredients_df_all %>% cbind (word_count = sapply(1:length(ingredients),function(i){wordcount(ingredients[i])}) ) %>% data.frame(stringsAsFactors=FALSE) 

one_word_ingredients <-ingredients_df_all[ingredients_df_all$word_count==1,]$ingredients
one_word_ingredients <- gsub(" ", "", one_word_ingredients, fixed = TRUE) %>% data.frame(stringsAsFactors=FALSE)
more_word_ingredients <- ingredients_df_all[ingredients_df_all$word_count>1,]
```

```{r}
train_nd <- train
train_nd$ingredients <- lapply(train_nd$ingredients,unique)
train_nd$ingredients[1]
```
```{r}
ingredients[ingredients %in% (train_nd$ingredients[1] %>% unlist)] %>% list
train_nd$ingredients[[1]][train_nd$ingredients[[1]] %in% (ingredients)]
train_nd$ingredients <-lapply(1:nrow(train),function(i){ train_nd$ingredients[[i]][train_nd$ingredients[[i]] %in% (ingredients)] })
```


```{r}
head(train_nd)
```

### Filtrar por nombres clave

```{r}
# write_csv(ingredients_count %>%
#        filter(freq > 200) %>% 
#        select(-id) %>%
#        arrange(freq), "data/ingredients_top300.csv")
a <- c("pinto_beans", "pitted_kalamata_olives", "bacon_slices", "mashed_potatoes", "sour_cream", "sour_crema")

# gsub("(.*)(beans?|olives?|tabasco|potato(es)?|cilantro|wheat|shiitake|lemon|chives?|tomato(es)?|cabbage|peanut|yogh?o?urt|rice|onions?|ginger|sesame|jalapeno|stock|bacon|monterey_jack|vinegar|sausages?|mozz?arell?a|monterey_jack|feta|ricotta|dijon|masala|eggs?|coconut_milk|cheddar|dijon|parmesan|sour_(crema|cream)|steak|pork|beef|chicken|oyster|garlic|salt|curry).*", "\\2", a)
a
rm(a)
```

